version: '3.7'

networks:
  bft:
    external: true
    name: fabric-bft

services:
  couchdb0orgA:
    image: couchdb:3.3.3
    labels:
      service: hyperledger-fabric
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    hostname: couchdb0orgA
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    deploy:
        mode: replicated
        replicas: 1
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
        placement:
          constraints:
            - node.hostname == vm1bft
    ports:
      - "5984:5984"
    networks:
      bft:
        aliases:
          - couchdb0orgA


  couchdb1orgA:
    image: couchdb:3.3.3
    labels:
      service: hyperledger-fabric
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    hostname: couchdb1orgA
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    deploy:
        mode: replicated
        replicas: 1
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
        placement:
          constraints:
            - node.hostname == vm1bft
    ports:
      - "8984:5984"
    networks:
      bft:
        aliases:
          - couchdb1orgA

