version: '3.7'

networks:
  raft:
    external: true
    name: fabric-raft

services:
  couchdb0orgC:
    image: couchdb:3.3.3
    labels:
      service: hyperledger-fabric
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    hostname: couchdb0orgC
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    deploy:
        mode: replicated
        replicas: 1
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
        placement:
          constraints:
            - node.hostname == vm3raft
    ports:
      - "7984:5984"
    networks:
      raft:
        aliases:
          - couchdb0orgC

  couchdb1orgC:
    image: couchdb:3.3.3
    labels:
      service: hyperledger-fabric
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    hostname: couchdb1orgC
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    deploy:
        mode: replicated
        replicas: 1
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
        placement:
          constraints:
            - node.hostname == vm3raft
    ports:
      - "10984:5984"
    networks:
      raft:
        aliases:
          - couchdb1orgC
